// <auto-generated />
using System;
using ApiApp.Helpers.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PermisosApp.Migrations
{
    [DbContext(typeof(PermisosContext))]
    [Migration("20230502230910_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("ApiApp.Models.Permission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserPermissionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UserPermissionID");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("ApiApp.Models.PermissionType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("PermissionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Enfermedad"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Diligencias"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Otros"
                        });
                });

            modelBuilder.Entity("ApiApp.Models.Permission", b =>
                {
                    b.HasOne("ApiApp.Models.PermissionType", "UserPermission")
                        .WithMany()
                        .HasForeignKey("UserPermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPermission");
                });
#pragma warning restore 612, 618
        }
    }
}
